import Contact from './Contact.vue'

export const contactComponents = [
    {
        variant: 'contact.basic',
        component: Contact,
        createDefaultProps: () => ({
            heading: 'Contact',
            name: '',
            role: '',
            bio: '',
            email: '',
            phone: '',
            address: '',
            city: '',
            country: '',
            website: '',
            linkedin: '',
            github: '',
            skills: '',
            languages: '',
            specialization: '',
            education: [],
            experience: [],
            imageSrc: '',
            photoFit: 'cover' as const,
            photoSize: 160,
            photoPosX: 50,
            photoPosY: 50,
            showPhoto: true,
            showName: true,
            showRole: true,
            showBio: true,
            showEmail: true,
            showPhone: true,
            showAddress: true,
            showCity: true,
            showCountry: true,
            showWebsite: true,
            showLinkedin: true,
            showGithub: true,
            showSkills: true,
            showLanguages: true,
            showSpecialization: true,
            showEducation: true,
            showExperience: true,
            style: {
                padTop: 0,
                padRight: 0,
                padBottom: 0,
                padLeft: 0,
                photoSize: 160,
            },
        }),
    },
] as const
